
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package pasito.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 37;
  public static final int GT = 72;
  public static final int DIVASSIGN = 75;
  public static final int CHANNEL = 71;
  public static final int TYPE = 10;
  public static final int GO = 20;
  public static final int CONST = 14;
  public static final int NOTEQ = 62;
  public static final int INT32 = 30;
  public static final int GE = 73;
  public static final int STRING_LIT = 34;
  public static final int FUNC = 6;
  public static final int RBRACK = 47;
  public static final int DEFER = 19;
  public static final int COMMA = 50;
  public static final int ANDASSIGN = 61;
  public static final int LBRACK = 46;
  public static final int LT = 43;
  public static final int STRUCT = 9;
  public static final int MODASSIGN = 79;
  public static final int DASSIGN = 49;
  public static final int FALSE = 29;
  public static final int NOT = 52;
  public static final int DOTDOTDOT = 53;
  public static final int PLUSASSIGN = 60;
  public static final int LE = 67;
  public static final int VAR = 15;
  public static final int GOTO = 21;
  public static final int PACKAGE = 4;
  public static final int EQ = 40;
  public static final int LSHIFTASSIGN = 76;
  public static final int MOD = 77;
  public static final int SELECT = 23;
  public static final int FALLTHROUGH = 56;
  public static final int TRUE = 28;
  public static final int PLUS = 35;
  public static final int LPAR = 41;
  public static final int ASSIGN = 48;
  public static final int INTERFACE = 7;
  public static final int BOOLEAN = 27;
  public static final int CHAN = 17;
  public static final int SWITCH = 12;
  public static final int FOR = 24;
  public static final int DIV = 38;
  public static final int FLOAT64 = 31;
  public static final int RETURN = 25;
  public static final int BITOR = 63;
  public static final int ELSE = 11;
  public static final int BREAK = 16;
  public static final int DOT = 55;
  public static final int MAP = 22;
  public static final int EOF = 0;
  public static final int SEMICOLON = 51;
  public static final int RPAR = 42;
  public static final int DEFAULT = 3;
  public static final int RSBRACK = 45;
  public static final int FLOAT_NUMBER = 33;
  public static final int IMPORT = 5;
  public static final int BITCLRASSIGN = 82;
  public static final int TIMESASSIGN = 69;
  public static final int MINUS = 36;
  public static final int BITAND = 59;
  public static final int ORASSIGN = 65;
  public static final int OR = 66;
  public static final int error = 1;
  public static final int CONTINUE = 18;
  public static final int IF = 13;
  public static final int BITXOR = 68;
  public static final int ID = 2;
  public static final int MINUSMINUS = 58;
  public static final int LSBRACK = 44;
  public static final int COLON = 54;
  public static final int INT_NUMBER = 32;
  public static final int RSHIFTASSIGN = 80;
  public static final int MINUSASSIGN = 64;
  public static final int CASE = 8;
  public static final int PLUSPLUS = 57;
  public static final int RSHIFT = 78;
  public static final int RANGE = 26;
  public static final int BITCLR = 81;
  public static final int AND = 39;
  public static final int LSHIFT = 74;
  public static final int EXCLORASSIGN = 70;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "DEFAULT",
  "PACKAGE",
  "IMPORT",
  "FUNC",
  "INTERFACE",
  "CASE",
  "STRUCT",
  "TYPE",
  "ELSE",
  "SWITCH",
  "IF",
  "CONST",
  "VAR",
  "BREAK",
  "CHAN",
  "CONTINUE",
  "DEFER",
  "GO",
  "GOTO",
  "MAP",
  "SELECT",
  "FOR",
  "RETURN",
  "RANGE",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "INT32",
  "FLOAT64",
  "INT_NUMBER",
  "FLOAT_NUMBER",
  "STRING_LIT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "EQ",
  "LPAR",
  "RPAR",
  "LT",
  "LSBRACK",
  "RSBRACK",
  "LBRACK",
  "RBRACK",
  "ASSIGN",
  "DASSIGN",
  "COMMA",
  "SEMICOLON",
  "NOT",
  "DOTDOTDOT",
  "COLON",
  "DOT",
  "FALLTHROUGH",
  "PLUSPLUS",
  "MINUSMINUS",
  "BITAND",
  "PLUSASSIGN",
  "ANDASSIGN",
  "NOTEQ",
  "BITOR",
  "MINUSASSIGN",
  "ORASSIGN",
  "OR",
  "LE",
  "BITXOR",
  "TIMESASSIGN",
  "EXCLORASSIGN",
  "CHANNEL",
  "GT",
  "GE",
  "LSHIFT",
  "DIVASSIGN",
  "LSHIFTASSIGN",
  "MOD",
  "RSHIFT",
  "MODASSIGN",
  "RSHIFTASSIGN",
  "BITCLR",
  "BITCLRASSIGN"
  };
}

